config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  devise_for :users

  resources :portfolios, except: :new do
    resources :tags, only: [:create, :destroy], param: :tag_id, controller: :portfolio_tags
    resources :blocks, only: [:index, :create, :destroy]
    resources :profiles, only: [:index, :update]
    resources :experiences, only: [:index, :create, :destroy]
  end

  resources :tags, only: :index
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  MAX_NUMBER_OF_TAGS = 4

  belongs_to :user

  has_one :profile
  has_one :about

  has_many :blocks
  has_many :portfolio_tags
  has_many :tags, through: :portfolio_tags
  has_many :educations
  has_many :experiences
  has_many :hobbies
  has_many :skills
  has_many :languages
  has_many :socials
  has_many :contacts
  has_many :additional_informations

  validates :slug, presence: true, uniqueness: true
  validates :tags, length: { in: 0..MAX_NUMBER_OF_TAGS, message: "can't have more than #{MAX_NUMBER_OF_TAGS} tags" }


  enum temp_avatar: { blue_robot: 0, green_robot: 1, orange_red_robot: 2, purple_robot: 3, red_robot: 4, yellow_robot: 5 }


  before_create :set_random_temp_avatar
  
  before_validation :set_slug, on: :create


  private


  def set_random_temp_avatar
    avatars_list = Portfolio.temp_avatars.keys
    self.temp_avatar = avatars_list.sample
  end

  def set_slug # Repare que movemos a chamada do service de gerador de slugs do PortfoliosController para o model Portfolio. Fizemos isso para separar melhor as responsabilidades.
    if self.slug.nil?
      slug_generator = PortfolioSlugGeneratorService.new
      self.slug = slug_generator.call
    end
  end
  
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :load_portfolios, only: :index
  before_action :load_portfolio, only: [:edit, :update]


  def index
    authorize(Portfolio)
  end


  def create
  	build_portfolio
    authorize @portfolio
    @portfolio.save
    redirect_to edit_portfolio_path(@portfolio)
  end


  def show
    @portfolio = Portfolio.find(params[:id])
    authorize @portfolio
    render json: { portfolio: @portfolio }, include: { tags: { only: [:id, :title] } }, status: :ok
  end


  def edit
    authorize @portfolio
  end


  def update
    build_portfolio
    authorize @portfolio
    save_and_render
  end


  private


  def save_and_render
    if @portfolio.save
      head :ok
    else
      render json: { errors: @portfolio.errors.full_messages, portfolio: @portfolio.reload }, status: :unprocessable_entity
    end
  end


  def build_portfolio
    @portfolio ||= portfolio_scope.build
    @portfolio.attributes = portfolio_params
  end


  def portfolio_params
    return {} unless params.has_key?(:portfolio)
    params.require(:portfolio).permit(:slug, :listed, :active, :remote_ok)
  end


  def load_portfolio
    @portfolio = portfolio_scope.find(params[:id])
  end


  def load_portfolios
    @portfolios = portfolio_scope.all
  end


  def portfolio_scope
    policy_scope(Portfolio)
  end
end

app/helpers/portfolio_helper.rb
module PortfolioHelper

  def render_profile_photo(portfolio)
    if portfolio.profile.present? && portfolio.profile.photo.attached?
      image_url = url_for(portfolio.profile.photo.variant(resize: "62x62"))
    end
    image_url ||= "avatars/#{portfolio.temp_avatar}"
    image_tag image_url
  end


  def render_profile_name(portfolio)
    return portfolio.profile.name if portfolio.profile.present?
    "Ainda não preenchido"
  end


  def render_profile_title(portfolio)
    return portfolio.profile.title if portfolio.profile.present?
    "Ainda não preenchido"
  end


  def render_portfolio_tags(tags)
    disabled_tags_quant = Portfolio::MAX_NUMBER_OF_TAGS - tags.count
    tags.each { |tag| concat draw_tag(tag.title) }
    disabled_tags_quant.times { concat draw_tag(unused_label, color: "grey") }
  end


  private


  def unused_label
    content_tag :i, "Vázia"
  end


  def draw_tag(title, color: "blue-grey")
    content_tag :div, class: "col s12 m6 l6" do
      concat content_tag :span, title, class: "label #{color} #{color}-darken-5 #{color}-text text-lighten-4"
    end
  end
end

app/views/portfolios/_portfolio.html.erb
<div class="portfolio col s12 m3 l3">
  <div class="card-panel center">
    <div class="col s12 m12 l12">
      <a href="" class="remove-portfolio right custom-grey-text text-darken-2">
        <i class="fa fa-icon fa-times"></i>
      </a>
    </div>
    <div class="row"><%= render_profile_photo(portfolio) %></div>
    <span class="name grey-text text-darken-2"><%= render_profile_name(portfolio) %></span>
    <div class="label grey darken-3 grey-text text-lighten-2"><%= render_profile_title(portfolio) %></div>
    <div class="row tags">
      <% render_portfolio_tags(portfolio.tags) %>
    </div>
    <div class="row">
      <div class="col s6 m6 l6">
        <%= link_to "Editar", edit_portfolio_path(portfolio), class: "btn light-blue lighten-2 col m12 s12" %>
      </div>
      <div class="col s6 m6 l6">
        <%= link_to "Visualizar", portfolio, class: "btn orange darken-1 right col m12 s12" %>
      </div>
    </div>
  </div>
</div>

app/views/portfolios/edit.html.erb
<div id="portfolio-edit" data-portfolio="<%= @portfolio.id %>"></div>

app/views/portfolios/index.html.erb
<div class="row portfolios">
  <div class="col m12">
    <p class="custom-grey-text title">Seus Portfólios</p>
  </div>
  <%= render @portfolios %>
</div>

<div class="add-portfolio col s12 m3 l3">
    <div class="card-panel center">
        <%= link_to portfolios_path, method: :post, class: "new-portfolio" do %>
        	<%= image_tag("add_portfolio.png", width: "150px") %>
        <% end %>
    </div>
</div>